[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run dev"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000" 